### ISSUE TITLE
Optimierung

### ISSUE THREAD

**Issue by Mioriarty** [fschillerg/gtr#2]
Wenn das Skript zur Optimierung der Dateien so funktioniert, wie ich denke, ist es fehlerhaft und unvollständig:
1. WICHTIG: Ich speichere am Anfang meines Programms 2 Strings. Diese Zeilen beginnen mit Anführungszeichen, werden aber von deinem Skript als Kommentare erkannt und somit gelöscht
2. For Zeilenenden und -> können jegliche Klammern und Anführungzeochen weggekürzt werden

**Comment by janbaudisch** [comment]
Für die Strings müsste man wohl einen regulären Ausdruck nutzen, der -> erkennt und dann nicht löscht. (Würde dann zwar auch Kommentare mit -> nicht löschen, aber besser, als einen kompletten Kompiler zu bauen.)
Was die restlichen Zeichen angeht, sollte eigentlich kein Problem sein mit zusäzlichen Ausdrücken, die gegen den Quelltext getestet werden. Wenn du dich jetzt nicht draufstürzt würde ich schauen, dass ich es in der nächste Woche versuche.

**Comment by Mioriarty** [comment]
Die Kommentare mit den Pfeilen, werden wohl kein Problem sein, da Ti-Basic diesen Ausdruck sowieso als Zuweisung eines Strings interpretiert wird und damit eh einen Fehler wirft. Bei den zusätzlichen regulären Ausdrücken muss man aufpassen, da zB bei `Disp "` der Anfüjrungsstrich auf keinen Fall entfernt werden darf

**Comment by janbaudisch** [comment]
Vielleicht beschränken wir uns auf die Entfernung von Klammern und Kommentaren? Das mit den zusätzlichen Anführungszeichen ist mir etwas riskant...

**Comment by janbaudisch** [comment]
Das Problem ist jetzt behoben.
